import test from "node:test";
import assert from "node:assert/strict";
import crypto from "crypto";

// Provide required secrets for the modules under test BEFORE importing them.
process.env.AADHAAR_HMAC_PEPPER = process.env.AADHAAR_HMAC_PEPPER || "test-pepper-do-not-use-in-prod-0123456789";
process.env.AADHAAR_HMAC_PEPPER_VERSION = "1";
process.env.AADHAAR_FIELD_ENC_KEY =
  process.env.AADHAAR_FIELD_ENC_KEY || crypto.randomBytes(32).toString("base64");
process.env.AADHAAR_FIELD_ENC_KEY_VERSION = "1";

const { isValidAadhaarNumber, verhoeffValidate } = await import("../../utils/aadhaar/verhoeff.util.js");
const { computeAadhaarIdentityHash, computeAadhaarLookupHashes } = await import("../../utils/aadhaar/identityHash.util.js");
const { encryptField, decryptField, hashContact } = await import("../../utils/aadhaar/fieldEncryption.util.js");
const { validatePinStrength, hashPin, verifyPin } = await import("../../utils/aadhaar/pin.util.js");

/**
 * A small set of Aadhaar numbers with VALID Verhoeff check digits, generated by
 * appending the correct check digit. We compute them here so the test is
 * self-contained (no real Aadhaar numbers used).
 */
function withVerhoeffCheckDigit(elevenDigits) {
  // Compute the check digit that makes the 12-digit string Verhoeff-valid.
  const d = [
    [0,1,2,3,4,5,6,7,8,9],[1,2,3,4,0,6,7,8,9,5],[2,3,4,0,1,7,8,9,5,6],
    [3,4,0,1,2,8,9,5,6,7],[4,0,1,2,3,9,5,6,7,8],[5,9,8,7,6,0,4,3,2,1],
    [6,5,9,8,7,1,0,4,3,2],[7,6,5,9,8,2,1,0,4,3],[8,7,6,5,9,3,2,1,0,4],
    [9,8,7,6,5,4,3,2,1,0],
  ];
  const p = [
    [0,1,2,3,4,5,6,7,8,9],[1,5,7,6,2,8,3,0,9,4],[5,8,0,3,7,9,6,1,4,2],
    [8,9,1,6,0,4,3,5,2,7],[9,4,5,3,1,2,6,8,7,0],[4,2,8,6,5,7,3,9,0,1],
    [2,7,9,3,8,0,6,4,1,5],[7,0,4,6,9,1,3,2,5,8],
  ];
  const inv = [0,4,3,2,1,5,6,7,8,9];
  let c = 0;
  const reversed = elevenDigits.split("").reverse();
  // For check-digit generation, positions shift by 1 (index i+1).
  for (let i = 0; i < reversed.length; i++) {
    c = d[c][p[(i + 1) % 8][parseInt(reversed[i], 10)]];
  }
  return elevenDigits + inv[c];
}

test("Verhoeff: known valid and invalid numbers", () => {
  const valid = withVerhoeffCheckDigit("23456789012"); // 11 digits + check
  assert.equal(verhoeffValidate(valid), true);
  // Corrupt the check digit → invalid.
  const bad = valid.slice(0, 11) + ((parseInt(valid[11], 10) + 1) % 10);
  assert.equal(verhoeffValidate(bad), false);
});

test("isValidAadhaarNumber: format + checksum + first-digit rule", () => {
  const valid = withVerhoeffCheckDigit("23456789012");
  assert.equal(isValidAadhaarNumber(valid), true);
  assert.equal(isValidAadhaarNumber("1234"), false); // too short
  assert.equal(isValidAadhaarNumber("abcdefghijkl"), false); // non-numeric
  assert.equal(isValidAadhaarNumber("0" + valid.slice(1)), false); // first digit 0
});

test("identity hash: deterministic + pepper-dependent", () => {
  const num = withVerhoeffCheckDigit("23456789012");
  const a = computeAadhaarIdentityHash(num);
  const b = computeAadhaarIdentityHash(num);
  assert.equal(a.hash, b.hash, "same input+pepper → same hash");
  assert.equal(a.hash.length, 64, "sha256 hex");
  // Different Aadhaar → different hash.
  const other = computeAadhaarIdentityHash(withVerhoeffCheckDigit("34567890123"));
  assert.notEqual(a.hash, other.hash);
});

test("identity lookup hashes include previous peppers during rotation", () => {
  process.env.AADHAAR_HMAC_PEPPER_PREVIOUS = "old-pepper-1,old-pepper-2";
  const num = withVerhoeffCheckDigit("23456789012");
  const hashes = computeAadhaarLookupHashes(num);
  assert.equal(hashes.length, 3, "current + 2 previous");
  assert.equal(hashes[0].isCurrent, true);
  delete process.env.AADHAAR_HMAC_PEPPER_PREVIOUS;
});

test("field encryption: round-trips and detects tampering", () => {
  const plaintext = "Jane Doe, 123 Example Rd";
  const env = encryptField(plaintext);
  assert.notEqual(env, plaintext);
  assert.ok(env.startsWith("v1:"));
  assert.equal(decryptField(env), plaintext);
  // Tamper with ciphertext → GCM auth tag rejects.
  const parts = env.split(":");
  const tamperedCt = Buffer.from(parts[3], "base64");
  tamperedCt[0] ^= 0xff;
  parts[3] = tamperedCt.toString("base64");
  assert.throws(() => decryptField(parts.join(":")));
});

test("field encryption: null passes through", () => {
  assert.equal(encryptField(null), null);
  assert.equal(decryptField(null), null);
});

test("contact hashing is deterministic + case/space-insensitive", () => {
  assert.equal(hashContact("Test@Example.com"), hashContact(" test@example.com "));
  assert.equal(hashContact(""), null);
});

test("PIN strength: rejects weak PINs", () => {
  assert.equal(validatePinStrength("123456").valid, false, "sequential");
  assert.equal(validatePinStrength("654321").valid, false, "reverse sequential");
  assert.equal(validatePinStrength("111111").valid, false, "repeated");
  assert.equal(validatePinStrength("000000").valid, false, "denylist");
  assert.equal(validatePinStrength("123123").valid, false, "denylist");
  assert.equal(validatePinStrength("12345").valid, false, "too short");
  assert.equal(validatePinStrength("12ab56").valid, false, "non-numeric");
  assert.equal(validatePinStrength("428173").valid, true, "acceptable random PIN");
});

test("PIN hashing: verifies correct PIN and rejects wrong PIN", async () => {
  const { hash, salt, algo } = await hashPin("428173");
  assert.ok(["argon2id", "bcrypt"].includes(algo));
  assert.equal(await verifyPin("428173", hash, salt, algo), true);
  assert.equal(await verifyPin("999999", hash, salt, algo), false);
});
